### ISSUE TITLE
issue with node --experimental-modules index.mjs

### ISSUE THREAD

**Issue by Rinee-tel** [WebPlatformForEmbedded/Lightning#18]
Hi
I am trying to setup lightning sdk to run the examples available in the package.
Also , I created a file src/MyApp.js , index.html, generated a package.json inside src folder(without configuring any parameter) and also index.mjs , as mentioned in the documentation available in github.(Code part remains same as given in documentation https://webplatformforembedded.github.io/Lightning/docs/gettingStarted).

I tried running the command "node --experimental-modules index.mjs" in terminal and i got below error:
$ node --experimental-modules index.mjs
(node:16862) ExperimentalWarning: The ESM module loader is experimental.
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/test/rinee/Lightning/trial/src/node_modules/wpe-webgl/gles2.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

Then I tried removing --experimental-modules  and that also failed:
$ node index.mjs
/home/test/rinee/Lightning/trial/src/index.mjs:1
(function (exports, require, module, __filename, __dirname) { import lng from "wpe-lightning-node";                                                                                                 ^^^
           SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

Kindly help on this.
I am using node version v10.13.0.

**Comment by AerospaceGuy** [comment]
I'm also having this issue

**Comment by wilberhdez** [comment]
Somehow I think is easier following the "Lightning-SDK-blueprint" approach.  It worked for me -
 https://github.com/WebPlatformForEmbedded/Lightning-SDK-blueprint

**Comment by AerospaceGuy** [comment]
> Somehow I think is easier following the "Lightning-SDK-blueprint" approach. It worked for me -
> https://github.com/WebPlatformForEmbedded/Lightning-SDK-blueprint
> 
> Anyone know the difference between -
> Lightning-SDK-blueprint
> Lightning-SDK

Interesting, thanks I'll give that a shot

**Comment by wilberhdez** [comment]
I'm getting this error using this the same approach.   

$ node --experimental-modules index.mjs 
(node:22579) ExperimentalWarning: The ESM module loader is experimental.
{ Error: Cannot find module './build/Release/gles2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/lab/repos/test-lightning/Lightning/node_modules/wpe-webgl/gles2.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) code: 'MODULE_NOT_FOUND' }

**Comment by wilberhdez** [comment]
Okay this worked for me -

***First, install these dependencies:**
npm install canvas
sudo apt-get install libglew-dev libglfw3-dev
sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

***Then**
npm i https://github.com/WebPlatformForEmbedded/Lightning-node.git --save
node --experimental-modules index.mjs

**Comment by g-zachar** [comment]
I'm closing this issue for now, please reopen if still relevant.
