### ISSUE TITLE
Failed to execute 'texImage2D' on 'WebGLRenderingContext'

### ISSUE THREAD

**Issue by MykhailoDz** [WebPlatformForEmbedded/Lightning#53]
After updating Lightning to the newest version, it starts to show this error:

`WebPlatform.mjs:58 Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.
    at WebPlatform.uploadGlTexture (http://localhost:8080/build/bundle.js:46301:16)
    at WebGLRenderer.uploadTextureSource (http://localhost:8080/build/bundle.js:47787:29)
    at TextureManager._nativeUploadTextureSource (http://localhost:8080/build/bundle.js:57290:36)
    at TextureManager.uploadTextureSource (http://localhost:8080/build/bundle.js:57200:36)
    at TextureSource.setSource (http://localhost:8080/build/bundle.js:57575:26)
    at TextureSource.processLoadedSource (http://localhost:8080/build/bundle.js:57546:14)
    at TextureThrottler._processItem (http://localhost:8080/build/bundle.js:57723:20)
    at TextureThrottler.processSome (http://localhost:8080/build/bundle.js:57714:22)
    at Stage.drawFrame (http://localhost:8080/build/bundle.js:56065:31)
    at lp (http://localhost:8080/build/bundle.js:46290:28)`

**Comment by erikhaandrikman** [comment]
Can you share an isolated part of the code that causes this error?

**Comment by MykhailoDz** [comment]
` 
// Web-specific data types.
gl.texImage2D(gl.TEXTURE_2D, 0, options.internalFormat, options.format, options.type, source)` in WebPlatform.mjs;
and if you ask about personal code, we don't know, still trying to find out. There is no reference in error to our code.

**Comment by erikhaandrikman** [comment]
Yeah indeed some personal code so we can reproduce the error

**Comment by erikhaandrikman** [comment]
Yeah indeed some personal code so we can reproduce the error

**Comment by MykhailoDz** [comment]
@erikhaandrikman, we found the problem. 
In the newest version in lightning-web.js in createSvg function you delete : 
`            img.crossOrigin = "anonymous";
`
After adding it, everything works fine.

**Comment by erikhaandrikman** [comment]
thnx for the message we will take a look at it.

**Comment by WahajTariq** [comment]
Hello,

I wanted to use Cesium to verify the coordinates of a BIM Model (ifc imported). When I launch the HelloWorld program it gives me the following error:

An error occurred while rendering. Rendering has stopped.
SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.

Error: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
at new Texture (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:292351)
at Material$4.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:320751)
at EllipsoidPrimitive.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:2554722)
at Moon.update (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:2824039)
at Scene.updateEnvironment (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3102902)
at render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3106427)
at tryAndCatchError (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3106686)
at Scene.render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:48:3108572)
at CesiumWidget.render (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:90:113237)
at n (file:///C:/Users/vwaha/Downloads/Cesium-1.92/Build/Cesium/Cesium.js:90:98966

The image of the error:
![image](https://user-images.githubusercontent.com/83837323/162645255-be683677-4c99-43ed-b79f-c917e14d9b50.png)



Could you please help me to solve this?
